# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SArqTwqKrzq9kyn2r0s2qKagDozW52Se

1.	Defining the class or method for calculating the survival duration
"""

class SurvivalDurationCalculator:
    def __init__(self, age):
        self.age = age

    def calculate_duration(self, time_unit):
        # logic for calculating duration goes here
        pass

"""2.	Defining the logic for calculating the duration in 6 units."""

class SurvivalDurationCalculator:
    def __init__(self, age):
        self.age = age

    def calculate_duration(self, time_unit):
        if time_unit == 'months' or time_unit == 'm':
            return self.age * 12
        elif time_unit == 'weeks' or time_unit == 'w':
            return self.age * 52
        elif time_unit == 'days' or time_unit == 'd':
            return self.age * 365
        elif time_unit == 'hours' or time_unit == 'h':
            return self.age * 8760
        elif time_unit == 'minutes' or time_unit == 'min':
            return self.age * 525600
        elif time_unit == 'seconds' or time_unit == 's':
            return self.age * 31536000
        else:
            return "Invalid time unit"

"""Successful execution of the app without any errors, and giving the output ."""

calculator = SurvivalDurationCalculator(10)
print(calculator.calculate_duration('months'))  # Output: 120