# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZU25fXct4QcmkfASzFGtew5CSEtOWkHB
"""



"""**Python Project: Survival Duration Calculator**

Project description:

The objective of the project is to calculate the duration of how long a person lived based on his Age.
The duration should be calculated in different time units like Months, Weeks, Days, Hours, Minutes, Seconds.
The input to the application is an Age of a person and the output is expected to calculate the duration of time he lived in different time units as selected by the user.


Below is the expected output.
What's your age? 10
Please choose time unit: Months, Weeks, Days, Hours, Minutes, Seconds.
Note: You can write the first letter or the full name of the time unit. m
You lived for 120 Months

"""

def calculate_duration():
    age = int(input("What's your age? "))
    time_unit = input("Please choose time unit: ").lower()

    months = age * 12
    weeks = months * 4
    days = weeks * 7
    hours = days * 24
    minutes = hours * 60
    seconds = minutes * 60

    if time_unit == 'months' or time_unit == 'm':
        print(f"You lived for {months} Months")
    elif time_unit == 'weeks' or time_unit == 'w':
        print(f"You lived for {weeks} Weeks")
    elif time_unit == 'days' or time_unit == 'd':
        print(f"You lived for {days} Days")
    elif time_unit == 'hours' or time_unit == 'h':
        print(f"You lived for {hours} Hours")
    elif time_unit == 'minutes' or time_unit == 'min':
        print(f"You lived for {minutes} Minutes")
    elif time_unit == 'seconds' or time_unit == 's':
        print(f"You lived for {seconds} Seconds")
    else:
        print("Invalid time unit. Please choose from Months, Weeks, Days, Hours, Minutes, Seconds.")

calculate_duration()